---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: add nodejs repository
      command: bash -c 'curl -sL https://deb.nodesource.com/setup | sudo bash -'

    - name: update apt cache
      apt: update_cache=yes

    - name: setup basic software
      apt: name={{item}} state=latest
      with_items:
        - tmux
        - git

    - name: install system packages
      apt: name={{item}} state=latest
      with_items:
        - build-essential
        - nodejs
        - postgresql
        - libpq-dev
        - python-psycopg2

    - name: install npm packages
      npm: name={{item}} state=latest global=yes
      with_items:
        - grunt-cli
        - bower

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  tasks:
    - name: create user database
      postgresql_db: name=vagrant

    - name: create database user
      postgresql_user: db=vagrant name=vagrant password=password role_attr_flags=SUPERUSER priv=ALL

    - name: create production database
      postgresql_db: name=kcsrv owner=vagrant
